language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

env:
  - COMPOSER_FLAGS=""

matrix:
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-stable"
    - php: 7.1
      env: COMPOSER_FLAGS=""

install: composer update $COMPOSER_FLAGS --prefer-dist

script: vendor/bin/phpunit
